stages:
  - build
  - test
  - deploy

# Использование Docker без Docker-in-Docker
image: docker:latest

# Build stage: сборка Docker образов
build-job:
  stage: build
  script:
    - docker info
    - docker build -t backend .

test-job:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up -d

deploy-job:
  stage: deploy
  script:
    - echo "Deploy stage here"
